name: 'Run windup integration tests'

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-windup-test:
    name: Run windup tests
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
    strategy:
      fail-fast: false
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: konveyor/analyzer-lsp
        path: analyzer-lsp
    - name: build analyzer-lsp Dockerfile
      run: docker build -f analyzer-lsp/Dockerfile -t analyzer-lsp analyzer-lsp
    - name: build shim Dockerfile
      run: docker build -f Dockerfile -t testing .
    - name: Run windup tests
      run: (docker run testing test /windup-rulesets/rules/rules-reviewed/ | tee output.log) && tail -n1 output.log > pass_rate
    - name: Post result to PR
      uses: mshick/add-pr-comment@v2
      with:
        message-path: pass_rate
        refresh-message-position: true
        proxy-url: https://add-pr-comment-proxy-94idvmwyie-uc.a.run.app
