name: 'Run windup integration tests'

on:
  workflow_dispatch:
  pull_request_target:

jobs:
  run-windup-test:
    name: Run windup tests
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
    strategy:
      fail-fast: false
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: refs/pull/${{ github.event.number }}/merge
    - name: Checkout analyzer-lsp repo
      uses: actions/checkout@v3
      with:
        repository: konveyor/analyzer-lsp
        path: analyzer-lsp
    - name: build analyzer-lsp Dockerfile
      run: docker build -f analyzer-lsp/Dockerfile -t analyzer-lsp analyzer-lsp
    - name: build shim Dockerfile
      run: docker build -f Dockerfile -t testing .
    - name: Run windup tests
      run: (docker run testing test -fail-fast /windup-rulesets/rules/rules-reviewed/ | tee output.log) && tail -n1 output.log > pass_rate
    - name: Create comment
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: pass_rate
